#!/usr/bin/env bash
# This shell script packages a single folder into a zipped file, given the
# name of the folder.

if [ $# -ge 1 ] ; then
    tar cvf $1.tar $1/
    gzip $1.tar
    echo ""
    echo "Output: $1.tar.gz"
else
    echo "Usage: ./package_dir dirname"
fi
