#!/usr/bin/env python3
#
# This Python 3 script converts all known-format playlists in the current
# directory to be Android-compatible.

import argparse
import os
import sys

PLAYLIST_EXTENSIONS = ['.m3u', '.m3u8']

SOURCE_MUSIC_FILES_DIR = 'D:/Documents/Jeffrey/Gallery/Music/Music'
RESULT_MUSIC_FILES_DIR = '/usr0/Music'

if len(sys.argv) < 2:
    print("Usage: ./convert_to_android_playlists")
    sys.exit(1)

for ext in PLAYLIST_EXTENSIONS:
    if

current_dir = os.path.dirname(os.path.realpath(__file__))
with open(sys.argv[1], 'r') as fp:
    with open(current_dir + "/output.txt", 'w') as output_fp:
        line = fp.readline()
        while line:
            if line[0] == '#' and line.find(',') != -1:
                songstart = line.find(',') + 1
                output_fp.write(line[songstart:])
            line = fp.readline()
