#!/bin/sh

echo ""
echo "----- BEGIN INSTRUCTIONS FOR MANUAL CONFIGURATIONS -----"
echo ""
echo "Described below are configurations which cannot be done through the command line."
echo ""
echo "GUAKE-TERMINAL:"
echo ""
echo "  Execute $ guake --preferences"
echo ""
echo "  In the 'General' tab:"
echo "    Disable popup notifications on startup"
echo ""
echo "  In the 'Shell' tab (only if you installed zsh):"
echo "    Set default interpreter to /bin/zsh"
echo ""
echo "  In the 'Appearance' tab:"
echo "    Disable 'Use the system fixed width font' (only if you installed zsh)"
echo "    Select Font: 'Meslo LG M DZ for Powerline RegularForPowerline' (only if you installed zsh)"
echo "    Select Palette - Built-in scheme: 'Tomorrow Night Blue'"
echo "    Set Transparency: 25%"
echo ""
echo "----- END INSTRUCTIONS FOR MANUAL CONFIGURATIONS -----"
echo ""
