#!/bin/sh
#
# chkconfig: 345 99 84
# description:
#
# This script is a template for creating a Linux service to run a command.
#
# Above:
#   Fill in the description of the service, below the chkconfig line.
# Below:
#   Fill in the name, description, and command to run.
#   If you would like logging, change the output file from /dev/null.
# Rename this file to the name of your service.
# Place this file in /etc/init.d/
# Invoke the service using the following commands:
#   sudo service <script_name> start
#   sudo service <script_name> stop
#

NAME=
DESC=""
CMD=""
LOGFILE=/dev/null

PIDFILE=/var/run/${NAME}.pid

start()
{
  nohup ${CMD} >> ${LOGFILE} 2>&1 &
  echo $! > ${PIDFILE}
}

stop()
{
  kill $(cat ${PIDFILE});
  rm ${PIDFILE}
}

if [ $# -ge 1 ] ; then
  case "$1" in
    start)

      if [ ! -f ${PIDFILE} ] ; then
        echo "Starting service ${NAME}..."
        start
        echo "Started."
      else
        echo "Service ${NAME} is already running."
      fi

    ;;
    stop)

      if [ -f ${PIDFILE} ] ; then
       echo "Stopping service ${NAME}..."
       stop
       echo "Stopped."
      else
        echo "Service ${NAME} is not running."
      fi

    ;;
    restart)

      if [ -f ${PIDFILE} ] ; then
        echo "Restarting service ${NAME}..."
        stop
        echo "Stopped."
        start
        echo "Restarted."
      else
        echo "Service ${NAME} is not running."
      fi

    ;;
    info)

      echo ${DESC}

    ;;
    status)

      if [ -f ${PIDFILE} ] ; then
        echo "Service ${NAME} is running."
      else
        echo "Service ${NAME} is not running."
      fi

    ;;
  esac
else
  echo "Usage: service ${NAME} start|stop|restart|info|status"
fi
