#!/usr/bin/env python3
# This Python 3 script prints the given dimensions of all images in
# the current directory.
#
# Required pip packages:
#   Pillow

import os

# Local modules
import mediaUtils


if __name__ == '__main__':

    all_filenames = []
    all_dimensions = []

    # Collect dimensions
    for filename in os.listdir(os.getcwd()):
        if not mediaUtils.is_image_file(filename):
            continue

        all_filenames.append(filename)
        all_dimensions.append(mediaUtils.get_dimensions(filename))

    # Exit early if no files in directory
    if all_filenames == []:
        exit(0)

    # Print filenames and dimensions, formatted
    max_len = len( max(all_filenames, key=len) )

    for filename, dimensions in zip(all_filenames, all_dimensions):
        padding = max_len - len(filename) + 1
        print(filename + ":" + " "*padding +
            str(dimensions[0]) + " x " + str(dimensions[1]))
