#!/usr/bin/env python3
# This Python 3 script changes image file extensions to all lowercase.

import os
import sys

def isImageFile(filename):
    return filename.lower().endswith('.jpg') or \
            filename.lower().endswith('.jpeg') or \
            filename.lower().endswith('.png') or \
            filename.lower().endswith('.mov') or \
            filename.lower().endswith('.mp4') or \
            filename.lower().endswith('.avi')

if __name__ == '__main__':

    for filename in sorted(os.listdir(os.getcwd())):
        if not isImageFile(filename):
            continue

        # Cut out the extension
        last = 4
        if filename.lower().endswith('.jpeg'):
            last = 5
        extension = filename[-last:]

        if extension == extension.lower():
            continue

        # Format the new filename
        filename_base = filename[:filename.rfind('.')]
        extension = extension.lower()

        # Generate the new filename
        filename_new = filename_base + extension

        os.rename(filename, filename_new)
        print(filename_new)
