#!/usr/bin/env python3
# This Python 3 script changes image file extensions to all lowercase.

import os

# Local modules
import mediaUtils


if __name__ == '__main__':

    for filename in sorted(os.listdir(os.getcwd())):
        if not mediaUtils.is_image_file(filename):
            continue

        # Cut out the extension
        extension = mediaUtils.get_extension(filename)

        if extension == extension.lower():
            continue

        # Format the new filename
        filename_base = filename[:filename.rfind('.') + 1]
        extension = extension.lower()

        # Generate the new filename
        filename_new = filename_base + extension

        os.rename(filename, filename_new)
        print(filename_new)
