#!/usr/bin/env python3
# This Python 3 script numbers all images (png and jpg) starting from their
# lexigraphical order to be numbered as:
#
#   01 - .EXTENSION
#   02 - .EXTENSION
#   ...etc.
#
# An optional first argument sets the first number to start numbering files by.

import os
import sys

# Local modules
import mediaUtils


if __name__ == '__main__':

    # Optional argument: Number to start counting from
    if (len(sys.argv) == 2):
        number = int(sys.argv[1])
        if number < 0:
            print("Usage: ./number-img [firstNumber]")
            print("  firstNumber must be 0 or greater.")
            exit(1)
    else:
        number = 1

    for filename in sorted(os.listdir(os.getcwd())):
        if not mediaUtils.is_media_file(filename):
            continue

        # Generate the new filename
        number_str = str(number)
        if number < 10:
            number_str = '0' + number_str

        filename_new = number_str + ' - .' + mediaUtils.get_extension(filename)

        os.rename(filename, filename_new)
        print(filename_new)

        number += 1
