#!/usr/bin/env python3
# This Python 3 script numbers all images (png and jpg) starting from their
# lexigraphical order to be numbered as:
#
#   01 - .EXTENSION
#   02 - .EXTENSION
#   ...etc.

import os

def isImageFile(filename):
    return filename.lower().endswith('.jpg') or \
            filename.lower().endswith('.jpeg') or \
            filename.lower().endswith('.png')

if __name__ == '__main__':
    number = 1

    for filename in sorted(os.listdir(os.getcwd())):
        if not isImageFile(filename):
            continue

        # Cut out the extension
        last = 4
        if filename.lower().endswith('.jpeg'):
            last = 5
        extension = filename[-last:]

        # Generate the new filename
        number_str = str(number) if (number > 9) else '0'+str(number)
        filename_new = number_str + ' - ' + extension

        os.rename(filename, filename_new)
        print(filename_new)

        number += 1
