#!/usr/bin/env python3
# This Python 3 script resizes all images in the current directory to
# the given dimensions.
#
# Required pip packages:
#   Pillow
#   python-resize-image

import os
import sys
from PIL import Image, ImageFile
from resizeimage import resizeimage

ImageFile.LOAD_TRUNCATED_IMAGES = True

def resize_dimensions(filename, width, height):
    if width < 1 or height < 1:
        print("Width and height must be greater than 0.")
        exit(1)
    with open(filename, 'rb') as f:
        with Image.open(f) as image:
            new = resizeimage.resize_contain(image, [width, height])
            new = new.convert('RGB')
            new.save(filename, image.format)

def resize_percent(filename, pct):
    if pct < 1 or pct > 500:
        print("Percent must be between 1 and 500.")
        exit(1)
    pct *= 0.01

    with open(filename, 'rb') as f:
        with Image.open(f) as image:
            width_orig = image.size[0]
            height_orig = image.size[1]
    resize_dimensions(filename, int(width_orig * pct), int(height_orig * pct))

if __name__ == '__main__':
    if len(sys.argv) < 2:
        print("Usages: ./resize-img pct")
        print("        ./resize-img width height")
        exit(1)

    for filename in os.listdir(os.getcwd()):
        if not filename.lower().endswith('.jpg') and not filename.lower().endswith('.png'):
            continue

        if (len(sys.argv) == 3):
            width = int(sys.argv[1])
            height = int(sys.argv[2])
            resize_dimensions(filename, width, height)
        else:
            pct = float(sys.argv[1])
            resize_percent(filename, pct)

        print(filename)
