#!/usr/bin/env python3
# This Python 3 script resizes all images in the current directory to
# the given dimensions.
#
# Required pip packages:
#   Pillow
#   python-resize-image

import os
import sys
from PIL import Image, ImageFile
from resizeimage import resizeimage

# Local modules
import mediaUtils


if __name__ == '__main__':
    if len(sys.argv) < 2:
        print("Usages: ./resize-img pct")
        print("        ./resize-img width height")
        exit(1)

    for filename in os.listdir(os.getcwd()):
        if not mediaUtils.is_image_file(filename):
            continue

        if (len(sys.argv) == 3):
            width = int(sys.argv[1])
            height = int(sys.argv[2])
            mediaUtils.resize_dimensions(filename, width, height)
        else:
            pct = float(sys.argv[1])
            mediaUtils.resize_percent(filename, pct)
