#!/usr/bin/env python3
# This Python 3 script renames all files in the current directory with
# extensions jpeg (case-insensitive) to jpg.

import os

# Local modules
import mediaUtils


if __name__ == '__main__':
    for filename in os.listdir(os.getcwd()):
        extension = mediaUtils.get_extension(filename)

        if extension.lower() == 'jpeg':
            filename_new = filename[:-4] + 'jpg'
            path = os.path.join(os.getcwd(), filename)
            path_new = os.path.join(os.getcwd(), filename_new)

            os.rename(path, path_new)
            print(filename_new)
