#!/usr/bin/env python3
# This Python 3 script renames all jpg files to png in the current directory.

import os

if __name__ == '__main__':
    for filename in os.listdir(os.getcwd()):
        if filename.endswith('.jpg'):
            new_filename = filename[:-3] + 'png'
            os.rename(filename, new_filename)
            print(new_filename)
