#!/usr/bin/env python3
# This Python 3 script resizes all images in the current directory to
# the given dimensions.

import os
import sys
from PIL import Image
from resizeimage import resizeimage

def resize(filename, width, height):
    with open(filename, 'rb') as f:
        with Image.open(f) as image:
            new = resizeimage.resize_contain(image, [width, height])
            new.save(filename, image.format)

if __name__ == '__main__':
    if len(sys.argv) < 3:
        print("Usage: ./resize-img width height")
        exit(1)

    width = int(sys.argv[1])
    height = int(sys.argv[2])

    for filename in os.listdir(os.getcwd()):
        if filename.endswith('.jpg') or filename.endswith('.png'):
            resize(filename, width, height)
            print(filename)
