#!/usr/bin/env python3
# This Python 3 script renames all files in the current directory with
# extensions JPG, JPEG, or jpeg to jpg.

import os

if __name__ == '__main__':
    for filename in os.listdir(os.getcwd()):
        last = 0
        if filename.endswith('.JPG'):
            last = 3
        elif filename.endswith('.JPEG') or filename.endswith('.jpeg'):
            last = 4

        if last != 0:
            filename_new = filename[:-last] + 'jpg'
            os.rename(filename, filename_new)
            print(filename_new)
