#!/usr/bin/env python3
# This Python 3 script converts all filenames in the current directory
# to all-lowercase and converts all hyphens to underscores.

import os

current_file = os.path.abspath(__file__)

files = [f for f in os.listdir('.') if os.path.isfile(f)]
for f in files:
    f_new = f.lower().replace('-', '_')
    if f_new != f and os.path.abspath(f) != current_file:
        print(f)
        print(f_new)
        print()
        os.rename(f, f_new)

