#!/usr/bin/env bash
#
# This Bash script is to be run on the host machine BEFORE the network
# configuration is set up on the Beagle Bone.

# Find the following network adapter handles by running the folloiwng
# command on the host machine:
#
#     $ ifconfig
#
# and choosing the names of the two adapters with IP addresses.
NETWORK=wlp2s0
VIRT=enx883f4aaa871e

echo "Configuring IP tables to route properly..."
sudo iptables --table nat --append POSTROUTING --out-interface $NETWORK -j MASQUERADE
sudo iptables --append FORWARD --in-interface $VIRT -j ACCEPT

echo "Turning on IP forwarding..."
sudo sh -c "echo 1 > /proc/sys/net/ipv4/ip_forward"

echo
echo "To finish, configure the target device to use the host as the default gateway."

